### ISSUE TITLE
AsmToSMT: Error when creating yices context

### ISSUE THREAD

**Issue by moosbruggerj** [asmeta/asmeta#17]
When running AsmToSMT the application aborts with the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'yices_mk_context': /usr/lib/libyices.so: undefined symbol: yices_mk_context
	at com.sun.jna.Function.<init>(Function.java:179)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:391)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:371)
	at com.sun.jna.Library$Handler.invoke(Library.java:205)
	at com.sun.proxy.$Proxy2.yices_mk_context(Unknown Source)
	at org.asmeta.toyices.YicesModel.<init>(YicesModel.java:42)
	at org.asmeta.toyices.SMTbasedASMsimulator.<init>(SMTbasedASMsimulator.java:110)
	at org.asmeta.toyices.SMTbasedASMsimulator.<init>(SMTbasedASMsimulator.java:118)
	at org.asmeta.toyices.AsmToSMT.main(AsmToSMT.java:11)
```
yices version:
```
$ yices --version
Yices 2.6.2
Copyright SRI International.
Linked with GMP 6.2.1
Copyright Free Software Foundation, Inc.
Build date: 2020-12-18
Platform: x86_64-pc-linux-gnu (release)
```
using `nm -D /usr/lib/libyices.so` reveals that `yices_mk_context` is indeed missing in the library

**Comment by garganti** [comment]
I think it is because AsmetaSMT works only with yices 1.
